name: Bug report
description: Report a reproducible problem in Logister.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce and debug quickly.
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the observed behavior.
      placeholder: When I open the project inbox, rows disappear after filtering...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps and sample input/payloads where possible.
      placeholder: |
        1. Sign in as ...
        2. Open ...
        3. Click ...
        4. Observe ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide versions and runtime details.
      placeholder: Ruby 4.0.1, Rails 8.1.2, PostgreSQL 16, Redis 7, macOS 15
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and stacktrace
      description: Paste relevant logs, errors, screenshots, or trace IDs.
      render: shell
  - type: checkboxes
    id: contribution_model
    attributes:
      label: Contribution model
      options:
        - label: I understand code contributions are by maintainer invitation; issues are welcome from everyone.
          required: true
