name: Feature request
description: Suggest a product or developer-experience improvement.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What workflow or pain point is missing today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe behavior, API, and UX you want.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Who benefits and how?
  - type: checkboxes
    id: contribution_model
    attributes:
      label: Contribution model
      options:
        - label: I understand code contributions are by maintainer invitation; issues are welcome from everyone.
          required: true
